export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const COIN_ADD_FAIL = "COIN_ADD_FAIL";
export const COIN_ADD_REQUEST = "COIN_ADD_REQUEST";
export const COIN_ADD_SUCCESS = "COIN_ADD_SUCCESS";

export const COIN_GET_FAIL = "COIN_GET_FAIL";
export const COIN_GET_REQUEST = "COIN_GET_REQUEST";
export const COIN_GET_SUCCESS = "COIN_GET_SUCCESS";

export const REMOVE_ERROR = "REMOVE_ERROR";
